# AI-Assisted: generated by ChatGPT for the Aetheric Engine client tools.
import tempfile
import unittest
from pathlib import Path

from aetheric.parser import BINARY_HEADERS, StreamParser
from aetheric.storage import SQLiteStorage
from aetheric.validator import validate_capture


class ValidatorTests(unittest.TestCase):
    def test_validator_matches_capture(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            db_path = Path(tmpdir) / "ae.sqlite"
            capture_path = Path(tmpdir) / "capture.bin"

            parser = StreamParser()
            storage = SQLiteStorage(db_path)

            ascii_frame = b"$HELLO;"
            payload = b"xyz"
            binary_frame = bytes([BINARY_HEADERS[0]]) + len(payload).to_bytes(5, "big") + payload

            with open(capture_path, "wb") as fh:
                for chunk in (ascii_frame, binary_frame[:4], binary_frame[4:]):
                    fh.write(chunk)
                    ascii_msgs, binary_msgs = parser.feed(chunk)
                    storage.save_ascii(ascii_msgs)
                    storage.save_binary(binary_msgs)

            ascii_msgs, binary_msgs = parser.flush()
            storage.save_ascii(ascii_msgs)
            storage.save_binary(binary_msgs)
            storage.close()

            result = validate_capture(capture_path, db_path)
            self.assertTrue(result.ok, msg=f"Validation failed: {result}")


if __name__ == "__main__":
    unittest.main()
