# AI-Assisted: generated by ChatGPT for the Aetheric Engine client tools.
"""
SQLite persistence helpers for Aetheric Engine messages.

Schema is based on PLAN.md plus README.md suggestions:
- msgascii: payload TEXT, timestamp, idx autoincrement.
- msgbinary: header, payload blob, declared/received length, truncated flag, timestamp, idx autoincrement.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Iterable

from .parser import AsciiMessage, BinaryMessage


DDL_ASCII = """
CREATE TABLE IF NOT EXISTS msgascii (
    payload TEXT,
    ts INTEGER DEFAULT CURRENT_TIMESTAMP,
    idx INTEGER PRIMARY KEY AUTOINCREMENT
)
"""

DDL_BINARY = """
CREATE TABLE IF NOT EXISTS msgbinary (
    header INTEGER,
    payload BLOB,
    declared_len INTEGER,
    received_len INTEGER,
    ts INTEGER DEFAULT CURRENT_TIMESTAMP,
    idx INTEGER PRIMARY KEY AUTOINCREMENT,
    truncated INTEGER DEFAULT 0
)
"""


class SQLiteStorage:
    def __init__(self, db_path: Path) -> None:
        self.db_path = Path(db_path)
        self.conn = sqlite3.connect(self.db_path)
        self.conn.execute("PRAGMA journal_mode=WAL;")
        self._ensure_schema()

    def _ensure_schema(self) -> None:
        cur = self.conn.cursor()
        cur.execute(DDL_ASCII)
        cur.execute(DDL_BINARY)
        self.conn.commit()

    def save_ascii(self, messages: Iterable[AsciiMessage]) -> int:
        rows = [(m.payload,) for m in messages]
        if not rows:
            return 0
        self.conn.executemany("INSERT INTO msgascii(payload) VALUES (?)", rows)
        self.conn.commit()
        return len(rows)

    def save_binary(self, messages: Iterable[BinaryMessage]) -> int:
        rows = [
            (
                m.header,
                sqlite3.Binary(m.payload),
                m.declared_len,
                m.received_len,
                int(bool(m.truncated)),
            )
            for m in messages
        ]
        if not rows:
            return 0
        self.conn.executemany(
            "INSERT INTO msgbinary(header, payload, declared_len, received_len, truncated) VALUES (?, ?, ?, ?, ?)",
            rows,
        )
        self.conn.commit()
        return len(rows)

    def close(self) -> None:
        self.conn.close()

    def __enter__(self) -> "SQLiteStorage":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()
