#!/usr/bin/env python3
# AI-Assisted: generated by ChatGPT for quick AE connectivity probing.
"""
Minimal socket probe for AE endpoints.

Connects to host:port, optionally sends AUTH <JWT>, then reads for a short window
to confirm the server responds. Captures a preview of bytes received.
"""

from __future__ import annotations

import argparse
import binascii
import socket
import time
from typing import Tuple


def hexdump(data: bytes, limit: int = 64) -> str:
    chunk = data[:limit]
    return binascii.hexlify(chunk).decode("ascii")


def probe(
    host: str,
    port: int,
    jwt: str | None,
    duration: float,
    timeout: float,
    read_size: int,
) -> Tuple[int, bytes]:
    """
    Returns total bytes read and a preview sample.
    """
    total = 0
    preview = bytearray()

    with socket.create_connection((host, port), timeout=timeout) as sock:
        sock.settimeout(timeout)
        if jwt:
            sock.sendall(f"AUTH {jwt}\n".encode("ascii"))

        end_time = time.time() + duration
        while time.time() < end_time:
            remaining = end_time - time.time()
            sock.settimeout(max(0.1, min(timeout, remaining)))
            try:
                data = sock.recv(read_size)
            except socket.timeout:
                continue

            if not data:
                break

            total += len(data)
            if len(preview) < 128:
                preview.extend(data[: 128 - len(preview)])

    return total, bytes(preview)


def main() -> int:
    parser = argparse.ArgumentParser(description="Quick AE socket probe")
    parser.add_argument("--host", required=True, help="AE host")
    parser.add_argument("--port", required=True, type=int, help="AE port")
    parser.add_argument("--jwt", help="JWT token for AUTH")
    parser.add_argument("--duration", type=float, default=10.0, help="Seconds to read")
    parser.add_argument("--timeout", type=float, default=5.0, help="Socket timeout seconds")
    parser.add_argument("--read-size", type=int, default=4096, help="Bytes per recv")
    args = parser.parse_args()

    try:
        total, preview = probe(
            host=args.host,
            port=args.port,
            jwt=args.jwt,
            duration=args.duration,
            timeout=args.timeout,
            read_size=args.read_size,
        )
    except Exception as exc:  # pragma: no cover - manual probe utility
        print(f"[!] Probe failed: {exc}")
        return 1

    print(f"[+] Probe complete: read {total} bytes over ~{args.duration}s")
    if preview:
        print(f"[+] Preview ({len(preview)} bytes) hex: {hexdump(preview)}")
    else:
        print("[!] No data received; check JWT, host/port, or increase duration/timeout")
    return 0


if __name__ == "__main__":  # pragma: no cover - manual probe utility
    raise SystemExit(main())
